function Main() {
  return(
    <main className="main">
      <h2 className="main-title">Lorem, ipsum dolor.</h2>
      <p className="main-parr">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, debitis libero quos velit id illum, quas repellat quibusdam maxime molestiae blanditiis quasi eveniet neque pariatur sequi. Officiis cum eos nostrum omnis, maiores enim consectetur temporibus laudantium hic eius consequuntur veritatis quidem inventore ullam esse. Ipsam possimus est numquam culpa explicabo!</p>
      <h2 className="main-title">Lorem ipsum dolor sit.</h2>
      <p className="main-parr">Quisquam consequatur vitae impedit, inventore reprehenderit rem illo natus voluptate odio atque ea quia neque voluptates nihil pariatur corporis repellendus reiciendis! Nesciunt dolorum perspiciatis doloribus architecto magni numquam omnis ex sint error reiciendis, accusantium iusto magnam ut porro deserunt! Iusto porro beatae suscipit quia dolorum tenetur ab rerum sed ad?</p>
      <h2 className="main-title">Natus molestias labore nisi?</h2>
      <p className="main-parr">Dolor iste, consequuntur reiciendis est modi velit esse iure illo deserunt sunt eos voluptatibus enim hic voluptates perferendis, expedita nulla quisquam? Nam aut alias eum officia animi cupiditate quos labore quaerat! Mollitia enim explicabo aspernatur aperiam provident ullam atque possimus fugit perferendis recusandae dolorem necessitatibus, assumenda doloremque exercitationem accusamus harum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quos mollitia iusto consectetur itaque rerum laborum id, voluptates ipsam! Possimus accusantium recusandae quos fugiat quia dicta est officiis rerum culpa.</p>
      <p>Nobis molestiae non quod similique veritatis excepturi atque quo libero at! Impedit voluptatem molestias repellat, eligendi est nemo voluptatum hic laudantium. A asperiores omnis explicabo quidem, facere dolores doloremque laboriosam.</p>
      <p>Ea soluta earum suscipit provident nesciunt, autem fuga perferendis quos nobis a, laborum et aliquam excepturi veritatis explicabo repudiandae dolor voluptas, est iure odio vel minima corrupti perspiciatis necessitatibus. Earum!</p>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores dolorum dicta aliquid? Quas, mollitia quaerat ducimus laboriosam accusantium laborum explicabo sint beatae, dicta aspernatur nemo libero voluptatem, modi nobis vero asperiores architecto ipsum veritatis culpa laudantium cum et? Porro est labore cupiditate quibusdam maiores accusamus animi quod, officiis quia in expedita inventore a adipisci deserunt, perspiciatis necessitatibus neque velit soluta. Soluta ut saepe veritatis ex voluptate, ea modi atque quaerat quae asperiores dolore dicta minus dolorem. Quasi, temporibus corporis consequatur sed in doloribus sit, voluptatibus delectus et modi aliquid fugiat possimus dolores veritatis laboriosam accusamus, omnis deleniti! Odit, consequatur voluptatibus!</p>
      <p>Autem deserunt enim officia libero itaque expedita eaque atque error debitis. Fugit vitae culpa pariatur earum magnam reprehenderit sapiente dicta, nostrum a amet illo sunt eius distinctio temporibus laboriosam quas quisquam. Repellat veniam laboriosam totam exercitationem atque iste vero deleniti animi consectetur beatae. Expedita soluta explicabo rem temporibus quam. Cumque beatae praesentium aliquid hic necessitatibus nam ad magni molestias doloribus facere dicta ratione accusamus, ut ipsam vel dolor tenetur sed cupiditate reprehenderit. Eveniet blanditiis similique dolore laboriosam hic quas ipsam perferendis velit iste mollitia porro maxime, a deserunt illum! Debitis, in? Soluta suscipit illum doloremque ducimus labore sint eligendi asperiores!</p>
      <p>Sunt, maxime! Atque libero repellat voluptas excepturi architecto quis sunt error amet, quam, earum eaque nesciunt incidunt mollitia. Amet vel debitis velit, officia minus magni veniam adipisci! Dolorem aspernatur, expedita cumque in libero corporis tenetur? Laboriosam sapiente facere quae, ipsa sed architecto sunt voluptatum obcaecati ab impedit reprehenderit dolore! Corporis, quasi reprehenderit sequi voluptatem delectus maiores. Dolorem repellat id doloremque accusamus maiores veritatis, aliquam dolorum ea neque voluptatum, corrupti cum et rerum architecto possimus dicta in error asperiores fuga ratione impedit vel molestias. Iure officiis reprehenderit illum at tenetur repudiandae, deserunt, sapiente consectetur rerum quia accusantium nostrum recusandae sint vero.</p>
    </main>

  )
}

export default Main;